version: '3'
services:
  web:
    container_name: 'linktree'
    environment:
      - NODE_ENV=docker-development
    build: .
    depends_on:
      - postgres    
    ports:
      - "8080:8080"
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: linktree_database_development
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"


