version: '3'
services:
  web:
    container_name: 'linktree'
    build: .
    depends_on:
      - postgres    
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: linktree_database_development
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"


